### ISSUE TITLE
Consider adding image_style_warmer to pre-generate all images for all image styles

### ISSUE THREAD

**Issue by olivierbouwman** [thinkshout/drupal-project#46]
Had issues on CLC where social sharing images were not being generated on request consistently. This solved it. Will also speed up initial page load for new content.

**Comment by mariacha** [comment]
@olivierbouwman Did this end up working nicely on CLC? Have you tried it out on any other sites?

**Comment by olivierbouwman** [comment]
Never did the level of social sharing on any other sites, never ran into the same issues because of that. I think we can table this for now and pick it up again if we run into it again.
