### ISSUE TITLE
Output behat results in format CircleCI likes for tests run on CI

### ISSUE THREAD

**Issue by tauno** [thinkshout/drupal-project#50]
Look at
https://github.com/leymannx/drupal-circleci-behat/blob/develop/.circleci/config.yml#L86-L92 and try to do something similar. I believe this will output nicer test data in the CircleCI failure reports. Might require updating the robo-drupal `test` command.

## Next steps
- [ ] Note that this is set up to happen on NCYL but has broken: https://app.circleci.com/pipelines/github/thinkshout/ncyl-ca/274/workflows/b79c1cdf-8f8b-4cc1-b32f-b6f675561a1d/jobs/303/tests so start by fixing that.
- [ ] Move the changes over to LVHN. There's a ticket that's related you can track time to: https://github.com/thinkshout/lvhn/issues/6050 -- My suspicion is that if we output behat tests in junit, we can also re-run only failed tests!
- [ ] Roll the out to changes required to `robo-drupal` (if any)
- [ ] If junit and only running failed tests works on LVHN, get a list of other sites using `robo` and  `behat` and create tickets for each of those to use the new robo and behat to output junit. Add instructions on how to implement to those tickets.
- [ ] Update https://library.thinkshoutlabs.com/articles/new-site-setup-ticket-template-wordpress-and-drupal in the Behat section to include the changes needed to send behat results to junit.

**Comment by tauno** [comment]
These changes on NCYL https://github.com/thinkshout/ncyl/commit/829e2554bdf97da2a519772fea7117073910180f result in this nicer output of failures:
![image](https://user-images.githubusercontent.com/250188/51147707-291fbd00-1810-11e9-9500-1421c8744e34.png)

**Comment by mariacha** [comment]
I've moved this to https://github.com/thinkshout/support/issues/78 so am closing.
