### ISSUE TITLE
Add visual regression dependencies to nginx-php-fpm

### ISSUE THREAD

**Issue by olivierbouwman** [thinkshout/drupal-project#52]
https://github.com/thinkshout/nginx-php-fpm
Needs:
- [ ] apk add --update jq
- [ ] apk add --update nodejs nodejs-npm

Currently in use on feeding-america and cls8

**Comment by olivierbouwman** [comment]
WIP: https://github.com/thinkshout/nginx-php-fpm/tree/php72-screener
https://github.com/thinkshout/nginx-php-fpm/pull/2

**Comment by mariacha** [comment]
This ia long done.
