### ISSUE TITLE
Drupal 9 deprecation prep

### ISSUE THREAD

**Issue by mariacha** [thinkshout/drupal-project#53]
See if we can incorporate any kind of D9 deprecation tool like https://github.com/mglaman/drupal-check

- [ ] Set up the Drupal Check command line tool on a site
- [ ] Add that check to a circle build.
- [ ] Pull the changes into our Drupal Project.

**Comment by mariacha** [comment]
Thought from slack: We could install this globally on circle to run the checks if there are too many conflicts within the project files.

**Comment by nrackleff** [comment]
I didn't have much luck installing in a project, or globally as noted in the May 2nd conversation in the tech-talk channel, so I am trying the upgrade status module https://www.drupal.org/project/upgrade_status.

But... when I use `composer require 'drupal/upgrade_status:^1.0'` I see `mglaman/phpstan-drupal 0.11.3 requires webflo/drupal-finder ^1.1 -> satisfiable by webflo/drupal-finder[1.1.0] but these conflict with your requirements or minimum-stability.` Looking at that now.

**Comment by nrackleff** [comment]
I added the upgrade_status module, but it appears to have an issue where it is not displaying anything after scan. Next step will be to try the patch for the issue https://www.drupal.org/project/upgrade_status/issues/3053781

**Comment by nrackleff** [comment]
@mariacha  I had a little time today, so I updated to the dev version and applied the ^^ patch. I'm still not seeing data after the scan runs. I will report that on the drupal.org issue.

**Comment by nrackleff** [comment]
@mariacha They released a new alpha3 version of the module today. I'm giving it a try now. :-)

**Comment by nrackleff** [comment]
No luck. I actually created a new issue. https://www.drupal.org/project/upgrade_status/issues/3058022

**Comment by mariacha** [comment]
Dang!

**Comment by nrackleff** [comment]
I took a few minutes this morning to provide the maintainer with some detailed information of what I did and what the messages were. https://www.drupal.org/project/upgrade_status/issues/3058022#comment-13131301 Hopefully it will help solve the problems.

**Comment by mariacha** [comment]
Thanks for keeping ahold of this thread!

**Comment by nrackleff** [comment]
Still working with the maintainer. https://www.drupal.org/project/upgrade_status/issues/3058022#comment-13132810

**Comment by nrackleff** [comment]
@mariacha Looks like our issue is being closed as it is likely cause by another. Our original issue: https://www.drupal.org/project/upgrade_status/issues/3058022#comment-13146039
New issue: https://www.drupal.org/project/upgrade_status/issues/3050653

**Comment by nrackleff** [comment]
@mariacha I tested the alpha4 and it did not solve the problem. I have not yet tried it on simplytest.me, but will do so when I don't have billable work taking priority.

**Comment by nrackleff** [comment]
@mariacha Alpha 5 worked and the original issue is solved. https://www.drupal.org/project/upgrade_status/issues/3058022#comment-13169965 
It did, however, uncover another issue where it will implode if any of the modules themselves throw uncaught exceptions during the scan process. https://www.drupal.org/project/upgrade_status/issues/3065760 
In our case with the basic drupal-project it was the redirect module, which can be fixed by updating the redirect module to 1.4 (June 22 release). The maintainers of the upgrade status module are working to fix this.

**Comment by mariacha** [comment]
Perfect! Can you add this module and the updated redirect version to the composer.json file for this project? Leave the `upgrade_status` module as a dev dependency.

**Comment by nrackleff** [comment]
@mariacha I've updated the redirect module to v1.4 and moved upgrade_status to the require-dev section. Scan completes now. I'm attaching the report. Github won't let me attach .html file, so i've renamed it with a .txt extension. Just switch it back to .html if you want to view it. 
[upgrade-status-export-2019-07-11T08_31_20-0700.txt](https://github.com/thinkshout/drupal-project/files/3382795/upgrade-status-export-2019-07-11T08_31_20-0700.txt)

**Comment by mariacha** [comment]
Sweet! I opened a PR based on your work, which has failing circle tests. I suspect it's unrelated to your work though, and that the project has some bad stuff in its composer file, based on the file Ben committed for Freedom House's initial build: https://github.com/thinkshout/freedomhouse/blob/master/composer.json

Now. Is there a command line tool to run this check?

**Comment by nrackleff** [comment]
@mariacha  I have asked about command line. https://www.drupal.org/project/upgrade_status/issues/3067415 
I also see there is a beta version now, so I will update to that. 
Are the failing tests something you want me to address, or are you going to revert Ben's Freedom House code?

**Comment by mariacha** [comment]
@nrackleff If you have time and interest I'd love if you could fix the tests. Otherwise I'll get to it eventually. Or someone will.

**Comment by nrackleff** [comment]
@mariacha No drush command, but there is this tool that Gábor mentioned is his reply. https://github.com/mglaman/drupal-check See his response to my question. https://www.drupal.org/project/upgrade_status/issues/3067415#comment-13180374

**Comment by mariacha** [comment]
Cool, seems like a good way forward then.

**Comment by mariacha** [comment]
TODO here: See if we can get Circle to scan through our internal custom modules and code to check compatibility.

Method forward might be:

- [ ] Create a branch on a recent project -- maybe start with a new one
- [ ] Get circle to do the scan (things will probably fail start) Andy mentions this for auto-fixing code:
https://github.com/palantirnet/drupal-rector
- [ ] This will probably block merge to master, so we'll have a sense of how long it takes to fix.

Goals:
1. Getting sites in Drupal 8 running Drupal 9 code 
2. Secondary goal: Keeping us from regressing to Drupal 8 code until we're fully upgraded to D9.

**Comment by mariacha** [comment]
Maria is working on some of this for Forum.

**Comment by mariacha** [comment]
TODO: Check with Gabe on how they implement this during the Mailchimp sprint.

**Comment by mariacha** [comment]
Drupal 9 is all done, and I think we are catching Drupal 10 deprecations pretty well via the DrupalStandard command phpcs, so I'm closing
