### ISSUE TITLE
Allow php 7.3

### ISSUE THREAD

**Issue by mariacha** [thinkshout/drupal-project#82]
We can now use php 7.3. Here's what would need to be updated:
https://github.com/thinkshout/encp-covid/compare/php73?expand=1

**Comment by mariacha** [comment]
@unclegcb This is pretty straightforward if anyone has time to do it.

**Comment by aprice42** [comment]
Padding this a little to make time to get drupal-project up and running locally.

**Comment by mariacha** [comment]
This is done. Yaay!
