### ISSUE TITLE
Run Screener tests on Circle

### ISSUE THREAD

**Issue by mariacha** [thinkshout/drupal-project#83]
Items to do here:
- [ ] Move the Screener tests out of Pantheon and into Circle.
- [ ] Figure out how to get some default content in that build ^. Ideas:
- [ ] (relatively easy) Pull in the database from one of the Pantheon sites (using Terminus). Note, a copy of the database could also be saved in Circle as an "Artifact", and occasionally refreshed.
- [ ] (more difficult) Do something more clever to create "dummy data". Ideas might be... migration from a spreadsheet, some modules...

**Comment by mariacha** [comment]
@olivierbouwman Throwing to you to see if this makes sense for FIPA. We might also work on it as part of https://github.com/thinkshout/lvhn/issues/1899 if we ever get to work on that one.

**Comment by olivierbouwman** [comment]
https://github.com/thinkshout/financial-planning-association/compare/screenerci?expand=1

- [ ] Images not working yet.
- [ ] Decide on database/file source.
Went for using Pantheon live right now which is not ideal. Could use develop or special regression specific multidev, have to decide if we run a backup every time or not. Right now develop had no backup and it seemed a little crazy to create a backup every time we run it so I switched it to live for now. Perhaps we create a new backup only when none exists or when it's too old.

**Comment by mariacha** [comment]
Awesome! I bet you can get images working if you set up Circle to be a "local" environment, so stage file proxy will work, and you wouldn't have to pull down the files. I would have thought that `drush config-import -y` would do it, but maybe we have circle set up to be `drush csim` is necessary to make sure to get the "config-local" settings.

**Comment by olivierbouwman** [comment]
It seems stage_file_proxy is enabled and has the right settings but it's not working for some reason, not seeing why yet. Attempting the hotlink option in stage_file_proxy to see if that helps. UPDATE: hotlinking doesn't seem to fix this. Perhaps images are just not being served properly from this server setup?

**Comment by mariacha** [comment]
Since we're letting go of Screener, I'm closing this one.
